version: '3'
services:
  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "33086:3306"
    restart: always
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --innodb_monitor_enable=all, --max-connections=1001]
    environment:
      - MYSQL_DATABASE=hrmusic
      - MYSQL_USER=hrmusic
      - MYSQL_PASSWORD=HRmusic@1234
      - MYSQL_ROOT_PASSWORD=HRmusic@1234
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin_master:
    restart: always
    image: phpmyadmin/phpmyadmin:5.1.1
    ports:
    - 8086:80
    environment:
      PMA_HOSTS: mysql


  app:
    restart: always
    build: .
    volumes:
      - .:/heartexercise_server
    image: app:heartexercise_server
    container_name: heartexercise_server
    command: >
     sh -c "cp .env_simple .env && python manage.py collectstatic --noinput && python manage.py makemigrations &&
             python manage.py migrate &&   
             python manage.py shell < create_root.py &&  
             uwsgi --ini uwsgi.ini"
    ports:
      - "8006:8006"
    depends_on:
      - mysql
