# Generated by Django 3.2.4 on 2021-06-17 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('place', models.IntegerField(choices=[('Zone 1', 1), ('Zone 1', 2), ('Zone 3', 3), ('Zone 4', 4)])),
                ('duration', models.DateField()),
                ('rest', models.IntegerField(choices=[('Zone 1', 1), ('Zone 1', 2), ('Zone 3', 3), ('Zone 4', 4)])),
                ('rest_duration', models.DateField()),
                ('reps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HeartSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(blank=True, null=True, upload_to='')),
                ('place', models.IntegerField(choices=[('Zone 1', 1), ('Zone 1', 2), ('Zone 3', 3), ('Zone 4', 4)])),
                ('heartrate', models.FloatField(default=70.1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('difficulty', models.IntegerField(choices=[('Easy', 1), ('Moderate', 2), ('Hard', 3)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.ManyToManyField(to='exercise.Duration')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('coach_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_day', models.IntegerField(default=1)),
                ('day_traning_program', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ManyToManyField(to='exercise.Program')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('running_distance', models.IntegerField(default=1)),
                ('race_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ManyToManyField(to='exercise.Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
