# Generated by Django 3.2.4 on 2021-06-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20210617_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='duration',
            name='place',
            field=models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4')]),
        ),
        migrations.AlterField(
            model_name='duration',
            name='rest',
            field=models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4')]),
        ),
        migrations.AlterField(
            model_name='duration',
            name='rest_duration',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='heartsong',
            name='place',
            field=models.IntegerField(choices=[(1, 'Zone 1'), (2, 'Zone 2'), (3, 'Zone 3'), (4, 'Zone 4')]),
        ),
        migrations.AlterField(
            model_name='program',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Easy'), (2, 'Moderate'), (3, 'Hard')]),
        ),
    ]
