# Generated by Django 3.2.4 on 2021-06-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20210617_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duration',
            options={'ordering': ['no']},
        ),
        migrations.AlterField(
            model_name='duration',
            name='no',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
