# Generated by Django 3.2.4 on 2021-06-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20210617_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan',
            new_name='program',
        ),
    ]
